services:
  confluence:
    image: atlassian/confluence
    restart: always
    ports:
      - 8090:8090
      - 8091:8091
    environment:
      ATL_JDBC_URL: jdbc:postgresql://db:5432/confluence
      ATL_JDBC_USER: dbuser
      ATL_JDBC_PASSWORD: mypassword
      ATL_DB_TYPE: postgresql
    volumes:
      - confluence:/var/atlassian/application-data/confluence
    depends_on: 
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  confluence:
  db:
